baseURL = "https://blog.nice2cu1.top/"
languageCode = "zh-cn"
title = "å¼ ä¸€æ¸…çš„éƒ¨è½é˜"
theme = "github-style"

[params]
  author = "å¼ ä¸€æ¸…"
  description = "In solitude, where we are least alone."
  github = "nice2cu1"
  email = "nice2cu1@outlook.com"
  url = "https://blog.nice2cu1.top/"
  keywords = "blog"
  rss = true
  lastmod = true
  favicon = "/images/github.png"
  location = "China"
  userStatusEmoji = "ğŸ˜€"
  enableGitalk = false
    
  [params.gitalk]
    clientID = "Your client ID" # Your client ID
    clientSecret = "Your client secret" # Your client secret
    repo = "LuvSia" # æ‚¨çš„åšå®¢çš„githubåœ°å€Repository nameï¼Œä¾‹å¦‚ï¼šxxxx.github.io
    owner = "ventusoon" # æ‚¨çš„GitHub ID
    admin = "ventusoon" # æ‚¨çš„GitHub ID
    id = "location.pathname" # æ–‡ç« é¡µé¢çš„é“¾æ¥åœ°å€å°±æ˜¯ID
    labels = "gitalk" # Github issue labels. If you used to use Gitment, you can change it
    perPage = 15 # Pagination size, with maximum 100.
    pagerDirection = "last" # Comment sorting direction, available values are 'last' and 'first'.
    createIssueManually = true # è®¾ç½®ä¸ºtrueï¼Œå¦‚æœæ˜¯ç®¡ç†å‘˜ç™»å½•ï¼Œä¼šè‡ªåŠ¨åˆ›å»ºissueï¼Œå¦‚æœæ˜¯falseï¼Œéœ€è¦ç®¡ç†å‘˜æ‰‹åŠ¨æ·»åŠ ç¬¬ä¸€ä¸ªè¯„è®º(issue)
    distractionFreeMode = false # Enable hot key (cmd|ctrl + enter) submit comment.    
    proxy = "https://cors-anywhere.azm.workers.dev/https://github.com/login/oauth/access_token" # å¯ä»¥è‡ªè¡Œæ·»åŠ åå‘ä»£ç†

[frontmatter]
  lastmod = ["lastmod", ":fileModTime", ":default"]
